services:
  - type: web
    name: car-price-prediction
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: FLASK_DEBUG
        value: "false"
    healthCheckPath: /

